param: { 
        drone_mass: 0.032,
        lin_drag_coeff: 0.000005,
        ang_drag_coeff: 0.000005,
        sim_period: 0.003,
        sensor_period: 0.003,
        sensor_noise: 0.001,
        x0: [0.0, 0.0, 0.0]
}

