anchors: [
        {id: 0, x: 2.6, y: -2.05, z: 0.0 },
        {id: 1, x: -2.66, y: -2.05, z: 0.0},
        {id: 2, x: -2.66, y: 1.47, z: 0.0},
        {id: 3, x: 2.6, y: 1.47, z: 0.74},
        {id: 4, x: -0.12, y: -2.1, z: 1.9},
        {id: 5, x: 1.62, y: -2.76, z: 1.4}
        ]
